// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiRateLimit struct {
	ID                  uuid.UUID
	ClientID            string
	Endpoint            string
	RequestsCount       int32
	WindowStart         time.Time
	CreatedAt           sql.NullTime
	ExcludeFromTracking sql.NullBool
}

// Archive of old rate limit records for historical analysis
type ApiRateLimitsArchive struct {
	ID                uuid.NullUUID
	ClientID          string
	Endpoint          string
	RequestsCount     int32
	WindowStart       time.Time
	ArchivedAt        sql.NullTime
	OriginalCreatedAt sql.NullTime
}

type AuditLog struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Action     string
	EntityType string
	EntityID   string
	OldValues  pqtype.NullRawMessage
	NewValues  pqtype.NullRawMessage
	IpAddress  sql.NullString
	UserAgent  sql.NullString
	CreatedAt  sql.NullTime
}

type Category struct {
	ID   int32
	Name string
}

type CurrentlyBlockedIp struct {
	ClientID      string
	Endpoint      string
	TotalAttempts int64
	LastAttempt   interface{}
	BlockWindows  int64
}

type DosageForm struct {
	ID   int32
	Name string
}

type LoginAttemptStat struct {
	Hour                int64
	TotalAttempts       int64
	Successful          int64
	Failed              int64
	RateLimitedAttempts int64
	UniqueIps           int64
	UniqueUsernames     int64
}

// Comprehensive logging of all login attempts with detailed user information for security auditing
type LoginAttemptsLog struct {
	ID                  uuid.UUID
	Username            string
	IpAddress           string
	UserAgent           sql.NullString
	AttemptTime         sql.NullTime
	Success             bool
	FailureReason       sql.NullString
	RateLimited         sql.NullBool
	RateLimitReleasedAt sql.NullTime
	ReleasedBy          sql.NullString
	SessionID           sql.NullString
	Country             sql.NullString
	City                sql.NullString
	DeviceInfo          pqtype.NullRawMessage
	CreatedAt           sql.NullTime
}

type Order struct {
	ID          uuid.UUID
	CreatedBy   uuid.NullUUID
	Status      string
	CreatedAt   sql.NullTime
	SubmittedAt sql.NullTime
	Notes       sql.NullString
	DeletedAt   sql.NullTime
}

type OrderItem struct {
	ID           uuid.UUID
	OrderID      uuid.NullUUID
	ProductID    uuid.NullUUID
	RequestedQty int32
	Unit         sql.NullString
	Note         sql.NullString
}

type Permission struct {
	ID          int32
	Name        string
	Resource    string
	Action      string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Product struct {
	ID           uuid.UUID
	Name         string
	Brand        sql.NullString
	DosageFormID sql.NullInt32
	Strength     sql.NullString
	Unit         sql.NullString
	CategoryID   sql.NullInt32
	Description  sql.NullString
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type ProductBarcode struct {
	ID          uuid.UUID
	ProductID   uuid.NullUUID
	Barcode     string
	BarcodeType sql.NullString
	CreatedAt   sql.NullTime
}

// Tracks when users are released from rate limiting, either automatically or manually
type RateLimitRelease struct {
	ID               uuid.UUID
	ClientID         string
	IpAddress        string
	Username         sql.NullString
	BlockedAt        time.Time
	ReleasedAt       sql.NullTime
	ReleasedBy       string
	ReleasedByUserID uuid.NullUUID
	BlockDuration    sql.NullInt64
	AttemptsCount    sql.NullInt32
	ReleaseReason    sql.NullString
	CreatedAt        sql.NullTime
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	ID           int32
	RoleID       int32
	PermissionID int32
	CreatedAt    sql.NullTime
}

// Tracks system initialization. Admin user must be created via secure setup endpoint with strong password.
type SystemSetup struct {
	ID               int32
	AdminCreated     sql.NullBool
	SetupCompletedAt sql.NullTime
	SetupByIp        sql.NullString
	CreatedAt        sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}
