// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiRateLimit struct {
	ID            uuid.UUID
	ClientID      string
	Endpoint      string
	RequestsCount int32
	WindowStart   time.Time
	CreatedAt     sql.NullTime
}

type AuditLog struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Action     string
	EntityType string
	EntityID   string
	OldValues  pqtype.NullRawMessage
	NewValues  pqtype.NullRawMessage
	IpAddress  sql.NullString
	UserAgent  sql.NullString
	CreatedAt  sql.NullTime
}

type Category struct {
	ID   int32
	Name string
}

type DosageForm struct {
	ID   int32
	Name string
}

type Order struct {
	ID          uuid.UUID
	CreatedBy   uuid.NullUUID
	Status      string
	CreatedAt   sql.NullTime
	SubmittedAt sql.NullTime
	Notes       sql.NullString
	DeletedAt   sql.NullTime
}

type OrderItem struct {
	ID           uuid.UUID
	OrderID      uuid.NullUUID
	ProductID    uuid.NullUUID
	RequestedQty int32
	Unit         sql.NullString
	Note         sql.NullString
}

type Permission struct {
	ID          int32
	Name        string
	Resource    string
	Action      string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Product struct {
	ID           uuid.UUID
	Name         string
	Brand        sql.NullString
	DosageFormID sql.NullInt32
	Strength     sql.NullString
	Unit         sql.NullString
	CategoryID   sql.NullInt32
	Description  sql.NullString
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type ProductBarcode struct {
	ID          uuid.UUID
	ProductID   uuid.NullUUID
	Barcode     string
	BarcodeType sql.NullString
	CreatedAt   sql.NullTime
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	ID           int32
	RoleID       int32
	PermissionID int32
	CreatedAt    sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}
