// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    created_by, status, notes
) VALUES (
    $1, $2, $3
)
RETURNING id, created_by, status, created_at, submitted_at, notes
`

type CreateOrderParams struct {
	CreatedBy uuid.NullUUID
	Status    string
	Notes     sql.NullString
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.CreatedBy, arg.Status, arg.Notes)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.Notes,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, requested_qty, unit, note
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, order_id, product_id, requested_qty, unit, note
`

type CreateOrderItemParams struct {
	OrderID      uuid.NullUUID
	ProductID    uuid.NullUUID
	RequestedQty int32
	Unit         sql.NullString
	Note         sql.NullString
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.RequestedQty,
		arg.Unit,
		arg.Note,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.RequestedQty,
		&i.Unit,
		&i.Note,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items WHERE id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItem, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, created_by, status, created_at, submitted_at, notes FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.Notes,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, product_id, requested_qty, unit, note FROM order_items
WHERE order_id = $1
ORDER BY id
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.NullUUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.RequestedQty,
			&i.Unit,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, created_by, status, created_at, submitted_at, notes FROM orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, created_by, status, created_at, submitted_at, notes FROM orders
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	CreatedBy uuid.NullUUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE order_items
SET 
    requested_qty = COALESCE($2, requested_qty),
    unit = COALESCE($3, unit),
    note = COALESCE($4, note)
WHERE id = $1
RETURNING id, order_id, product_id, requested_qty, unit, note
`

type UpdateOrderItemParams struct {
	ID           uuid.UUID
	RequestedQty int32
	Unit         sql.NullString
	Note         sql.NullString
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, updateOrderItem,
		arg.ID,
		arg.RequestedQty,
		arg.Unit,
		arg.Note,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.RequestedQty,
		&i.Unit,
		&i.Note,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET 
    status = $2,
    submitted_at = CASE WHEN $2 = 'submitted' THEN NOW() ELSE submitted_at END
WHERE id = $1
RETURNING id, created_by, status, created_at, submitted_at, notes
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.Notes,
	)
	return i, err
}
