// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name, brand, dosage_form_id, strength, unit, category_id, description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, brand, dosage_form_id, strength, unit, category_id, description, created_at, deleted_at
`

type CreateProductParams struct {
	Name         string
	Brand        sql.NullString
	DosageFormID sql.NullInt32
	Strength     sql.NullString
	Unit         sql.NullString
	CategoryID   sql.NullInt32
	Description  sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Brand,
		arg.DosageFormID,
		arg.Strength,
		arg.Unit,
		arg.CategoryID,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.DosageFormID,
		&i.Strength,
		&i.Unit,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, brand, dosage_form_id, strength, unit, category_id, description, created_at, deleted_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.DosageFormID,
		&i.Strength,
		&i.Unit,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, brand, dosage_form_id, strength, unit, category_id, description, created_at, deleted_at FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.DosageFormID,
			&i.Strength,
			&i.Unit,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, name, brand, dosage_form_id, strength, unit, category_id, description, created_at, deleted_at FROM products
WHERE 
    name ILIKE '%' || $1 || '%' 
    OR brand ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProductsParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.DosageFormID,
			&i.Strength,
			&i.Unit,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    name = COALESCE($2, name),
    brand = COALESCE($3, brand),
    dosage_form_id = COALESCE($4, dosage_form_id),
    strength = COALESCE($5, strength),
    unit = COALESCE($6, unit),
    category_id = COALESCE($7, category_id),
    description = COALESCE($8, description)
WHERE id = $1
RETURNING id, name, brand, dosage_form_id, strength, unit, category_id, description, created_at, deleted_at
`

type UpdateProductParams struct {
	ID           uuid.UUID
	Name         string
	Brand        sql.NullString
	DosageFormID sql.NullInt32
	Strength     sql.NullString
	Unit         sql.NullString
	CategoryID   sql.NullInt32
	Description  sql.NullString
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Brand,
		arg.DosageFormID,
		arg.Strength,
		arg.Unit,
		arg.CategoryID,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.DosageFormID,
		&i.Strength,
		&i.Unit,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
