// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setup.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const completeSystemSetup = `-- name: CompleteSystemSetup :one
UPDATE system_setup
SET 
    admin_created = $1,
    setup_completed_at = NOW(),
    setup_by_ip = $2
WHERE id = (SELECT id FROM system_setup ORDER BY created_at DESC LIMIT 1)
RETURNING id, admin_created, setup_completed_at, setup_by_ip, created_at
`

type CompleteSystemSetupParams struct {
	AdminCreated sql.NullBool
	SetupByIp    sql.NullString
}

func (q *Queries) CompleteSystemSetup(ctx context.Context, arg CompleteSystemSetupParams) (SystemSetup, error) {
	row := q.db.QueryRowContext(ctx, completeSystemSetup, arg.AdminCreated, arg.SetupByIp)
	var i SystemSetup
	err := row.Scan(
		&i.ID,
		&i.AdminCreated,
		&i.SetupCompletedAt,
		&i.SetupByIp,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (id, username, full_name, password_hash, role_id, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, username, full_name, password_hash, role_id, created_at, deleted_at
`

type CreateAdminUserParams struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.PasswordHash,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.RoleID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSystemSetupStatus = `-- name: GetSystemSetupStatus :one

SELECT id, admin_created, setup_completed_at, setup_by_ip, created_at FROM system_setup
ORDER BY created_at DESC
LIMIT 1
`

// internal/db/query/setup.sql
func (q *Queries) GetSystemSetupStatus(ctx context.Context) (SystemSetup, error) {
	row := q.db.QueryRowContext(ctx, getSystemSetupStatus)
	var i SystemSetup
	err := row.Scan(
		&i.ID,
		&i.AdminCreated,
		&i.SetupCompletedAt,
		&i.SetupByIp,
		&i.CreatedAt,
	)
	return i, err
}

const hasAdminUser = `-- name: HasAdminUser :one
SELECT EXISTS(
    SELECT 1 FROM users 
    WHERE role_id = 1 AND deleted_at IS NULL 
    LIMIT 1
) as has_admin
`

func (q *Queries) HasAdminUser(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasAdminUser)
	var has_admin bool
	err := row.Scan(&has_admin)
	return has_admin, err
}
