// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_optimized.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByUsernameWithRole = `-- name: GetUserByUsernameWithRole :one
SELECT 
    u.id,
    u.username,
    u.full_name,
    u.password_hash,
    u.role_id,
    u.created_at,
    u.deleted_at,
    r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.username = $1 AND u.deleted_at IS NULL
LIMIT 1
`

type GetUserByUsernameWithRoleRow struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	RoleName     sql.NullString
}

func (q *Queries) GetUserByUsernameWithRole(ctx context.Context, username string) (GetUserByUsernameWithRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameWithRole, username)
	var i GetUserByUsernameWithRoleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.RoleID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.RoleName,
	)
	return i, err
}

const getUserWithRole = `-- name: GetUserWithRole :one
SELECT 
    u.id,
    u.username,
    u.full_name,
    u.password_hash,
    u.role_id,
    u.created_at,
    u.deleted_at,
    r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.id = $1 AND u.deleted_at IS NULL
LIMIT 1
`

type GetUserWithRoleRow struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	RoleName     sql.NullString
}

func (q *Queries) GetUserWithRole(ctx context.Context, id uuid.UUID) (GetUserWithRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithRole, id)
	var i GetUserWithRoleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.RoleID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.RoleName,
	)
	return i, err
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT 
    u.id,
    u.username,
    u.full_name,
    u.password_hash,
    u.role_id,
    u.created_at,
    u.deleted_at,
    r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.deleted_at IS NULL AND u.role_id = $1
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersByRoleParams struct {
	RoleID sql.NullInt32
	Limit  int32
	Offset int32
}

type GetUsersByRoleRow struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	RoleName     sql.NullString
}

func (q *Queries) GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]GetUsersByRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByRole, arg.RoleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByRoleRow
	for rows.Next() {
		var i GetUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.RoleID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRoles = `-- name: ListUsersWithRoles :many

SELECT 
    u.id,
    u.username,
    u.full_name,
    u.password_hash,
    u.role_id,
    u.created_at,
    u.deleted_at,
    r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersWithRolesParams struct {
	Limit  int32
	Offset int32
}

type ListUsersWithRolesRow struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	RoleName     sql.NullString
}

// internal/db/query/users_optimized.sql
// Optimized queries to fix N+1 problem
func (q *Queries) ListUsersWithRoles(ctx context.Context, arg ListUsersWithRolesParams) ([]ListUsersWithRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithRolesRow
	for rows.Next() {
		var i ListUsersWithRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.RoleID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT 
    u.id,
    u.username,
    u.full_name,
    u.password_hash,
    u.role_id,
    u.created_at,
    u.deleted_at,
    r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.deleted_at IS NULL
  AND (
    u.username ILIKE '%' || $1 || '%' 
    OR u.full_name ILIKE '%' || $1 || '%'
  )
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
}

type SearchUsersRow struct {
	ID           uuid.UUID
	Username     string
	FullName     sql.NullString
	PasswordHash string
	RoleID       sql.NullInt32
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	RoleName     sql.NullString
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.PasswordHash,
			&i.RoleID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
